2024-02-05 09:46:36,024 [1;36mINFO[1;0m MainThread:11002 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-02-05 09:46:36,024 [1;36mINFO[1;0m MainThread:11002 [wandb_setup.py:_flush():76] Configure stats pid to 11002
2024-02-05 09:46:36,024 [1;36mINFO[1;0m MainThread:11002 [wandb_setup.py:_flush():76] Loading settings from /home/gert/.config/wandb/settings
2024-02-05 09:46:36,024 [1;36mINFO[1;0m MainThread:11002 [wandb_setup.py:_flush():76] Loading settings from /home/gert/ALPs_with_SWYFT/notebooks/stability_checks/all/wandb/settings
2024-02-05 09:46:36,024 [1;36mINFO[1;0m MainThread:11002 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-05 09:46:36,024 [1;36mINFO[1;0m MainThread:11002 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-05 09:46:36,024 [1;36mINFO[1;0m MainThread:11002 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-05 09:46:36,025 [1;36mINFO[1;0m MainThread:11002 [wandb_init.py:_log_setup():526] Logging user logs to ./wandb/run-20240205_094636-rv6i7gt1/logs/debug.log
2024-02-05 09:46:36,025 [1;36mINFO[1;0m MainThread:11002 [wandb_init.py:_log_setup():527] Logging internal logs to ./wandb/run-20240205_094636-rv6i7gt1/logs/debug-internal.log
2024-02-05 09:46:36,025 [1;36mINFO[1;0m MainThread:11002 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f11387a6ca0>
2024-02-05 09:46:36,025 [1;36mINFO[1;0m MainThread:11002 [wandb_init.py:init():566] calling init triggers
2024-02-05 09:46:36,025 [1;36mINFO[1;0m MainThread:11002 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-05 09:46:36,025 [1;36mINFO[1;0m MainThread:11002 [wandb_init.py:init():616] starting backend
2024-02-05 09:46:36,025 [1;36mINFO[1;0m MainThread:11002 [wandb_init.py:init():620] setting up manager
2024-02-05 09:46:36,027 [1;36mINFO[1;0m MainThread:11002 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-05 09:46:36,032 [1;36mINFO[1;0m MainThread:11002 [wandb_init.py:init():628] backend started and connected
2024-02-05 09:46:36,043 [1;36mINFO[1;0m MainThread:11002 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-02-05 09:46:36,045 [1;36mINFO[1;0m MainThread:11002 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-05 09:46:36,046 [1;36mINFO[1;0m MainThread:11002 [wandb_init.py:init():720] updated telemetry
2024-02-05 09:46:36,115 [1;36mINFO[1;0m MainThread:11002 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-05 09:46:37,847 [1;36mINFO[1;0m MainThread:11002 [wandb_run.py:_on_init():2254] communicating current version
2024-02-05 09:46:37,944 [1;36mINFO[1;0m MainThread:11002 [wandb_run.py:_on_init():2263] got version response 
2024-02-05 09:46:37,944 [1;36mINFO[1;0m MainThread:11002 [wandb_init.py:init():804] starting run threads in backend
2024-02-05 09:46:43,435 [1;36mINFO[1;0m MainThread:11002 [wandb_run.py:_console_start():2233] atexit reg
2024-02-05 09:46:43,436 [1;36mINFO[1;0m MainThread:11002 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2024-02-05 09:46:43,437 [1;36mINFO[1;0m MainThread:11002 [wandb_run.py:_redirect():2153] Wrapping output streams.
2024-02-05 09:46:43,437 [1;36mINFO[1;0m MainThread:11002 [wandb_run.py:_redirect():2178] Redirects installed.
2024-02-05 09:46:43,438 [1;36mINFO[1;0m MainThread:11002 [wandb_init.py:init():847] run started, returning control to user process
2024-02-05 09:46:43,439 [1;36mINFO[1;0m MainThread:11002 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-05 09:46:43,439 [1;36mINFO[1;0m MainThread:11002 [wandb_init.py:_pause_backend():437] pausing backend
2024-02-05 09:46:43,446 [1;36mINFO[1;0m MainThread:11002 [wandb_init.py:_resume_backend():442] resuming backend
2024-02-05 09:46:43,486 [1;36mINFO[1;0m MainThread:11002 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-05 09:46:43,486 [1;36mINFO[1;0m MainThread:11002 [wandb_init.py:_pause_backend():437] pausing backend
2024-02-05 09:46:43,499 [1;36mINFO[1;0m MainThread:11002 [wandb_init.py:_resume_backend():442] resuming backend
2024-02-05 09:46:43,502 [1;36mINFO[1;0m MainThread:11002 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-05 09:46:43,503 [1;36mINFO[1;0m MainThread:11002 [wandb_init.py:_pause_backend():437] pausing backend
2024-02-05 09:46:43,509 [1;36mINFO[1;0m MainThread:11002 [wandb_init.py:_resume_backend():442] resuming backend
2024-02-05 09:47:52,802 [1;36mINFO[1;0m MainThread:11002 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-05 09:47:52,803 [1;36mINFO[1;0m MainThread:11002 [wandb_init.py:_pause_backend():437] pausing backend
2024-02-05 09:47:52,811 [1;36mINFO[1;0m MainThread:11002 [wandb_init.py:_resume_backend():442] resuming backend
2024-02-05 09:47:52,814 [1;36mINFO[1;0m MainThread:11002 [wandb_run.py:_finish():1962] finishing run alps_with_swyft/lightning_logs/rv6i7gt1
2024-02-05 09:47:52,815 [1;36mINFO[1;0m MainThread:11002 [jupyter.py:save_history():445] not saving jupyter history
2024-02-05 09:47:52,815 [1;36mINFO[1;0m MainThread:11002 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-05 09:47:52,816 [1;36mINFO[1;0m MainThread:11002 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-05 09:47:52,816 [1;36mINFO[1;0m MainThread:11002 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-02-05 09:47:52,816 [1;36mINFO[1;0m MainThread:11002 [wandb_run.py:_restore():2185] restore
2024-02-05 09:47:52,817 [1;36mINFO[1;0m MainThread:11002 [wandb_run.py:_restore():2191] restore done
2024-02-05 09:48:03,615 [1;36mINFO[1;0m MainThread:11002 [wandb_run.py:_footer_history_summary_info():3857] rendering history
2024-02-05 09:48:03,616 [1;36mINFO[1;0m MainThread:11002 [wandb_run.py:_footer_history_summary_info():3889] rendering summary
2024-02-05 09:48:03,626 [1;36mINFO[1;0m MainThread:11002 [wandb_run.py:_footer_sync_info():3816] logging synced files
